//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTHOR
    {
        public decimal ID_AUTHOR { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<decimal> BIRTHYEAR { get; set; }
        public string BIRTHCOUNTRY { get; set; }
    }
}
