//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOK()
        {
            this.ORDERS = new HashSet<ORDERS>();
        }
    
        public decimal ID_BOOK { get; set; }
        public string BOOK_NAME { get; set; }
        public decimal PAGE_NUMBER { get; set; }
        public string ISBN { get; set; }
        public string BOOKBINDINGTYPE { get; set; }
        public decimal YEAR_OF_PUBLICATION { get; set; }
        public Nullable<decimal> BOOK_ID_PUBLISHINGHOUSE { get; set; }
        public string BOOK_LANGUAGE { get; set; }
        public string BOOK_DESCRIPTION { get; set; }
        public string BOOK_IMAGESOURCE { get; set; }
        public Nullable<decimal> NUMBERSOFBOOKS { get; set; }
        public decimal BOOK_PRISE { get; set; }
    
        public virtual PUBLISHERHOUSE PUBLISHERHOUSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS> ORDERS { get; set; }
    }
}
