//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTHOR> AUTHOR { get; set; }
        public virtual DbSet<BOOK> BOOK { get; set; }
        public virtual DbSet<GENRE> GENRE { get; set; }
        public virtual DbSet<ORDERINF> ORDERINF { get; set; }
        public virtual DbSet<PUBLISHERHOUSE> PUBLISHERHOUSE { get; set; }
        public virtual DbSet<USERACCOUNT> USERACCOUNT { get; set; }
        public virtual DbSet<USERINF> USERINF { get; set; }
        public virtual DbSet<ORDERS> ORDERS { get; set; }
    
        public virtual int ADD_AUTHORS(string pRC_AUTHOR, string pRC_FULLNAME, Nullable<decimal> pRC_BIRTHYEAR, string pRC_BIRTHCOUNTRY)
        {
            var pRC_AUTHORParameter = pRC_AUTHOR != null ?
                new ObjectParameter("PRC_AUTHOR", pRC_AUTHOR) :
                new ObjectParameter("PRC_AUTHOR", typeof(string));
    
            var pRC_FULLNAMEParameter = pRC_FULLNAME != null ?
                new ObjectParameter("PRC_FULLNAME", pRC_FULLNAME) :
                new ObjectParameter("PRC_FULLNAME", typeof(string));
    
            var pRC_BIRTHYEARParameter = pRC_BIRTHYEAR.HasValue ?
                new ObjectParameter("PRC_BIRTHYEAR", pRC_BIRTHYEAR) :
                new ObjectParameter("PRC_BIRTHYEAR", typeof(decimal));
    
            var pRC_BIRTHCOUNTRYParameter = pRC_BIRTHCOUNTRY != null ?
                new ObjectParameter("PRC_BIRTHCOUNTRY", pRC_BIRTHCOUNTRY) :
                new ObjectParameter("PRC_BIRTHCOUNTRY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_AUTHORS", pRC_AUTHORParameter, pRC_FULLNAMEParameter, pRC_BIRTHYEARParameter, pRC_BIRTHCOUNTRYParameter);
        }
    
        public virtual int ADD_GENRES(string pRC_GENRES)
        {
            var pRC_GENRESParameter = pRC_GENRES != null ?
                new ObjectParameter("PRC_GENRES", pRC_GENRES) :
                new ObjectParameter("PRC_GENRES", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_GENRES", pRC_GENRESParameter);
        }
    
        public virtual int ADD_NEW_BOOK(string aDDBOOKNAME, Nullable<decimal> aDDBOOKPAGES, string aDDBOOKISBN, string aDDBOOKBINDING, Nullable<decimal> aDDBOOKYEARPUBLIC, Nullable<decimal> aDDBOOKIDPUBLISHHOUS, string aDDBOOKLANGUAGE, string aDDBOOKDESCRIPT, string aDDBOOKIMAGESOURSCE, Nullable<decimal> aDDBOOKNUMBERSOFBOOKS, Nullable<decimal> aDDBOOKPRICE)
        {
            var aDDBOOKNAMEParameter = aDDBOOKNAME != null ?
                new ObjectParameter("ADDBOOKNAME", aDDBOOKNAME) :
                new ObjectParameter("ADDBOOKNAME", typeof(string));
    
            var aDDBOOKPAGESParameter = aDDBOOKPAGES.HasValue ?
                new ObjectParameter("ADDBOOKPAGES", aDDBOOKPAGES) :
                new ObjectParameter("ADDBOOKPAGES", typeof(decimal));
    
            var aDDBOOKISBNParameter = aDDBOOKISBN != null ?
                new ObjectParameter("ADDBOOKISBN", aDDBOOKISBN) :
                new ObjectParameter("ADDBOOKISBN", typeof(string));
    
            var aDDBOOKBINDINGParameter = aDDBOOKBINDING != null ?
                new ObjectParameter("ADDBOOKBINDING", aDDBOOKBINDING) :
                new ObjectParameter("ADDBOOKBINDING", typeof(string));
    
            var aDDBOOKYEARPUBLICParameter = aDDBOOKYEARPUBLIC.HasValue ?
                new ObjectParameter("ADDBOOKYEARPUBLIC", aDDBOOKYEARPUBLIC) :
                new ObjectParameter("ADDBOOKYEARPUBLIC", typeof(decimal));
    
            var aDDBOOKIDPUBLISHHOUSParameter = aDDBOOKIDPUBLISHHOUS.HasValue ?
                new ObjectParameter("ADDBOOKIDPUBLISHHOUS", aDDBOOKIDPUBLISHHOUS) :
                new ObjectParameter("ADDBOOKIDPUBLISHHOUS", typeof(decimal));
    
            var aDDBOOKLANGUAGEParameter = aDDBOOKLANGUAGE != null ?
                new ObjectParameter("ADDBOOKLANGUAGE", aDDBOOKLANGUAGE) :
                new ObjectParameter("ADDBOOKLANGUAGE", typeof(string));
    
            var aDDBOOKDESCRIPTParameter = aDDBOOKDESCRIPT != null ?
                new ObjectParameter("ADDBOOKDESCRIPT", aDDBOOKDESCRIPT) :
                new ObjectParameter("ADDBOOKDESCRIPT", typeof(string));
    
            var aDDBOOKIMAGESOURSCEParameter = aDDBOOKIMAGESOURSCE != null ?
                new ObjectParameter("ADDBOOKIMAGESOURSCE", aDDBOOKIMAGESOURSCE) :
                new ObjectParameter("ADDBOOKIMAGESOURSCE", typeof(string));
    
            var aDDBOOKNUMBERSOFBOOKSParameter = aDDBOOKNUMBERSOFBOOKS.HasValue ?
                new ObjectParameter("ADDBOOKNUMBERSOFBOOKS", aDDBOOKNUMBERSOFBOOKS) :
                new ObjectParameter("ADDBOOKNUMBERSOFBOOKS", typeof(decimal));
    
            var aDDBOOKPRICEParameter = aDDBOOKPRICE.HasValue ?
                new ObjectParameter("ADDBOOKPRICE", aDDBOOKPRICE) :
                new ObjectParameter("ADDBOOKPRICE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_NEW_BOOK", aDDBOOKNAMEParameter, aDDBOOKPAGESParameter, aDDBOOKISBNParameter, aDDBOOKBINDINGParameter, aDDBOOKYEARPUBLICParameter, aDDBOOKIDPUBLISHHOUSParameter, aDDBOOKLANGUAGEParameter, aDDBOOKDESCRIPTParameter, aDDBOOKIMAGESOURSCEParameter, aDDBOOKNUMBERSOFBOOKSParameter, aDDBOOKPRICEParameter);
        }
    
        public virtual int ADDNEWBOOK(string aDDBOOKNAME, Nullable<decimal> aDDBOOKPAGES, string aDDBOOKISBN, string aDDBOOKBINDING, Nullable<decimal> aDDBOOKYEARPUBLIC, Nullable<decimal> aDDBOOKIDPUBLISHHOUS, string aDDBOOKLANGUAGE, string aDDBOOKDESCRIPT, string aDDBOOKIMAGESOURSCE, Nullable<decimal> aDDBOOKNUMBERSOFBOOKS, Nullable<decimal> aDDBOOKPRICE)
        {
            var aDDBOOKNAMEParameter = aDDBOOKNAME != null ?
                new ObjectParameter("ADDBOOKNAME", aDDBOOKNAME) :
                new ObjectParameter("ADDBOOKNAME", typeof(string));
    
            var aDDBOOKPAGESParameter = aDDBOOKPAGES.HasValue ?
                new ObjectParameter("ADDBOOKPAGES", aDDBOOKPAGES) :
                new ObjectParameter("ADDBOOKPAGES", typeof(decimal));
    
            var aDDBOOKISBNParameter = aDDBOOKISBN != null ?
                new ObjectParameter("ADDBOOKISBN", aDDBOOKISBN) :
                new ObjectParameter("ADDBOOKISBN", typeof(string));
    
            var aDDBOOKBINDINGParameter = aDDBOOKBINDING != null ?
                new ObjectParameter("ADDBOOKBINDING", aDDBOOKBINDING) :
                new ObjectParameter("ADDBOOKBINDING", typeof(string));
    
            var aDDBOOKYEARPUBLICParameter = aDDBOOKYEARPUBLIC.HasValue ?
                new ObjectParameter("ADDBOOKYEARPUBLIC", aDDBOOKYEARPUBLIC) :
                new ObjectParameter("ADDBOOKYEARPUBLIC", typeof(decimal));
    
            var aDDBOOKIDPUBLISHHOUSParameter = aDDBOOKIDPUBLISHHOUS.HasValue ?
                new ObjectParameter("ADDBOOKIDPUBLISHHOUS", aDDBOOKIDPUBLISHHOUS) :
                new ObjectParameter("ADDBOOKIDPUBLISHHOUS", typeof(decimal));
    
            var aDDBOOKLANGUAGEParameter = aDDBOOKLANGUAGE != null ?
                new ObjectParameter("ADDBOOKLANGUAGE", aDDBOOKLANGUAGE) :
                new ObjectParameter("ADDBOOKLANGUAGE", typeof(string));
    
            var aDDBOOKDESCRIPTParameter = aDDBOOKDESCRIPT != null ?
                new ObjectParameter("ADDBOOKDESCRIPT", aDDBOOKDESCRIPT) :
                new ObjectParameter("ADDBOOKDESCRIPT", typeof(string));
    
            var aDDBOOKIMAGESOURSCEParameter = aDDBOOKIMAGESOURSCE != null ?
                new ObjectParameter("ADDBOOKIMAGESOURSCE", aDDBOOKIMAGESOURSCE) :
                new ObjectParameter("ADDBOOKIMAGESOURSCE", typeof(string));
    
            var aDDBOOKNUMBERSOFBOOKSParameter = aDDBOOKNUMBERSOFBOOKS.HasValue ?
                new ObjectParameter("ADDBOOKNUMBERSOFBOOKS", aDDBOOKNUMBERSOFBOOKS) :
                new ObjectParameter("ADDBOOKNUMBERSOFBOOKS", typeof(decimal));
    
            var aDDBOOKPRICEParameter = aDDBOOKPRICE.HasValue ?
                new ObjectParameter("ADDBOOKPRICE", aDDBOOKPRICE) :
                new ObjectParameter("ADDBOOKPRICE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADDNEWBOOK", aDDBOOKNAMEParameter, aDDBOOKPAGESParameter, aDDBOOKISBNParameter, aDDBOOKBINDINGParameter, aDDBOOKYEARPUBLICParameter, aDDBOOKIDPUBLISHHOUSParameter, aDDBOOKLANGUAGEParameter, aDDBOOKDESCRIPTParameter, aDDBOOKIMAGESOURSCEParameter, aDDBOOKNUMBERSOFBOOKSParameter, aDDBOOKPRICEParameter);
        }
    
        public virtual int BOOKALLINF()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BOOKALLINF");
        }
    
        public virtual ObjectResult<BOOKINF_Result> BOOKINF()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BOOKINF_Result>("BOOKINF");
        }
    
        public virtual int BOOKINFAVAILABILITY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BOOKINFAVAILABILITY");
        }
    
        public virtual int BOOKINF_NON_AVAILABILITY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BOOKINF_NON_AVAILABILITY");
        }
    
        public virtual int CHECKBOOKAVAILABILITYCURS(string bOOKNAME)
        {
            var bOOKNAMEParameter = bOOKNAME != null ?
                new ObjectParameter("BOOKNAME", bOOKNAME) :
                new ObjectParameter("BOOKNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CHECKBOOKAVAILABILITYCURS", bOOKNAMEParameter);
        }
    
        public virtual int ENTERUSER(string eNTEREDLOGIN, string eNTEREDPASSWORD, string eNTERENDFIO, string eNTEREDEMAIL, string eNTEREDNUMBER, string eNTEREDSEX, Nullable<System.DateTime> eNTEREDBIRTHDAY)
        {
            var eNTEREDLOGINParameter = eNTEREDLOGIN != null ?
                new ObjectParameter("ENTEREDLOGIN", eNTEREDLOGIN) :
                new ObjectParameter("ENTEREDLOGIN", typeof(string));
    
            var eNTEREDPASSWORDParameter = eNTEREDPASSWORD != null ?
                new ObjectParameter("ENTEREDPASSWORD", eNTEREDPASSWORD) :
                new ObjectParameter("ENTEREDPASSWORD", typeof(string));
    
            var eNTERENDFIOParameter = eNTERENDFIO != null ?
                new ObjectParameter("ENTERENDFIO", eNTERENDFIO) :
                new ObjectParameter("ENTERENDFIO", typeof(string));
    
            var eNTEREDEMAILParameter = eNTEREDEMAIL != null ?
                new ObjectParameter("ENTEREDEMAIL", eNTEREDEMAIL) :
                new ObjectParameter("ENTEREDEMAIL", typeof(string));
    
            var eNTEREDNUMBERParameter = eNTEREDNUMBER != null ?
                new ObjectParameter("ENTEREDNUMBER", eNTEREDNUMBER) :
                new ObjectParameter("ENTEREDNUMBER", typeof(string));
    
            var eNTEREDSEXParameter = eNTEREDSEX != null ?
                new ObjectParameter("ENTEREDSEX", eNTEREDSEX) :
                new ObjectParameter("ENTEREDSEX", typeof(string));
    
            var eNTEREDBIRTHDAYParameter = eNTEREDBIRTHDAY.HasValue ?
                new ObjectParameter("ENTEREDBIRTHDAY", eNTEREDBIRTHDAY) :
                new ObjectParameter("ENTEREDBIRTHDAY", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ENTERUSER", eNTEREDLOGINParameter, eNTEREDPASSWORDParameter, eNTERENDFIOParameter, eNTEREDEMAILParameter, eNTEREDNUMBERParameter, eNTEREDSEXParameter, eNTEREDBIRTHDAYParameter);
        }
    
        public virtual int EXPORT_AUTHORS_TO_XML()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EXPORT_AUTHORS_TO_XML");
        }
    
        public virtual int FIND_BOOKS_BY_TITLE(string tITLE)
        {
            var tITLEParameter = tITLE != null ?
                new ObjectParameter("TITLE", tITLE) :
                new ObjectParameter("TITLE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FIND_BOOKS_BY_TITLE", tITLEParameter);
        }
    
        public virtual int GETALLGENRESINF(Nullable<decimal> fUNC_BOOK_ID)
        {
            var fUNC_BOOK_IDParameter = fUNC_BOOK_ID.HasValue ?
                new ObjectParameter("FUNC_BOOK_ID", fUNC_BOOK_ID) :
                new ObjectParameter("FUNC_BOOK_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GETALLGENRESINF", fUNC_BOOK_IDParameter);
        }
    
        public virtual int GET_BOOK_BYAUTHOR(string p_AUTHORNAME)
        {
            var p_AUTHORNAMEParameter = p_AUTHORNAME != null ?
                new ObjectParameter("P_AUTHORNAME", p_AUTHORNAME) :
                new ObjectParameter("P_AUTHORNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_BOOK_BYAUTHOR", p_AUTHORNAMEParameter);
        }
    
        public virtual int GET_BOOK_BYGENRE(string p_NAMEGENREE)
        {
            var p_NAMEGENREEParameter = p_NAMEGENREE != null ?
                new ObjectParameter("P_NAMEGENREE", p_NAMEGENREE) :
                new ObjectParameter("P_NAMEGENREE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_BOOK_BYGENRE", p_NAMEGENREEParameter);
        }
    
        public virtual int GET_BOOK_BYLANGUAGE(string p_LANGUAGE)
        {
            var p_LANGUAGEParameter = p_LANGUAGE != null ?
                new ObjectParameter("P_LANGUAGE", p_LANGUAGE) :
                new ObjectParameter("P_LANGUAGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_BOOK_BYLANGUAGE", p_LANGUAGEParameter);
        }
    
        public virtual int GETORDERSINF()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GETORDERSINF");
        }
    
        public virtual int GETPUBLISHERINF(Nullable<decimal> fUNC_BOOK_ID)
        {
            var fUNC_BOOK_IDParameter = fUNC_BOOK_ID.HasValue ?
                new ObjectParameter("FUNC_BOOK_ID", fUNC_BOOK_ID) :
                new ObjectParameter("FUNC_BOOK_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GETPUBLISHERINF", fUNC_BOOK_IDParameter);
        }
    
        public virtual ObjectResult<GETUSERSINF_Result> GETUSERSINF()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETUSERSINF_Result>("GETUSERSINF");
        }
    
        public virtual int IMPORT_AUTHORS_FROM_XML()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IMPORT_AUTHORS_FROM_XML");
        }
    
        public virtual int INSERTHUGEDATA(Nullable<decimal> i, string tEXT)
        {
            var iParameter = i.HasValue ?
                new ObjectParameter("I", i) :
                new ObjectParameter("I", typeof(decimal));
    
            var tEXTParameter = tEXT != null ?
                new ObjectParameter("TEXT", tEXT) :
                new ObjectParameter("TEXT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTHUGEDATA", iParameter, tEXTParameter);
        }
    
        public virtual int INSERTORDERINF(Nullable<decimal> p_ID_ORDER, Nullable<decimal> p_ID_USER, Nullable<System.DateTime> p_ORDER_DATE, Nullable<System.DateTime> p_DELIVERY_TIME, Nullable<decimal> p_ID_ORDERS, Nullable<decimal> p_ID_BOOK, Nullable<decimal> p_NUMBERORDEREDBOOKS)
        {
            var p_ID_ORDERParameter = p_ID_ORDER.HasValue ?
                new ObjectParameter("P_ID_ORDER", p_ID_ORDER) :
                new ObjectParameter("P_ID_ORDER", typeof(decimal));
    
            var p_ID_USERParameter = p_ID_USER.HasValue ?
                new ObjectParameter("P_ID_USER", p_ID_USER) :
                new ObjectParameter("P_ID_USER", typeof(decimal));
    
            var p_ORDER_DATEParameter = p_ORDER_DATE.HasValue ?
                new ObjectParameter("P_ORDER_DATE", p_ORDER_DATE) :
                new ObjectParameter("P_ORDER_DATE", typeof(System.DateTime));
    
            var p_DELIVERY_TIMEParameter = p_DELIVERY_TIME.HasValue ?
                new ObjectParameter("P_DELIVERY_TIME", p_DELIVERY_TIME) :
                new ObjectParameter("P_DELIVERY_TIME", typeof(System.DateTime));
    
            var p_ID_ORDERSParameter = p_ID_ORDERS.HasValue ?
                new ObjectParameter("P_ID_ORDERS", p_ID_ORDERS) :
                new ObjectParameter("P_ID_ORDERS", typeof(decimal));
    
            var p_ID_BOOKParameter = p_ID_BOOK.HasValue ?
                new ObjectParameter("P_ID_BOOK", p_ID_BOOK) :
                new ObjectParameter("P_ID_BOOK", typeof(decimal));
    
            var p_NUMBERORDEREDBOOKSParameter = p_NUMBERORDEREDBOOKS.HasValue ?
                new ObjectParameter("P_NUMBERORDEREDBOOKS", p_NUMBERORDEREDBOOKS) :
                new ObjectParameter("P_NUMBERORDEREDBOOKS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTORDERINF", p_ID_ORDERParameter, p_ID_USERParameter, p_ORDER_DATEParameter, p_DELIVERY_TIMEParameter, p_ID_ORDERSParameter, p_ID_BOOKParameter, p_NUMBERORDEREDBOOKSParameter);
        }
    
        public virtual int SEARCH_BOOKS_BYPAGERANGE(Nullable<decimal> pRC_MIN_PAGES, Nullable<decimal> pRC_MAX_PAGES)
        {
            var pRC_MIN_PAGESParameter = pRC_MIN_PAGES.HasValue ?
                new ObjectParameter("PRC_MIN_PAGES", pRC_MIN_PAGES) :
                new ObjectParameter("PRC_MIN_PAGES", typeof(decimal));
    
            var pRC_MAX_PAGESParameter = pRC_MAX_PAGES.HasValue ?
                new ObjectParameter("PRC_MAX_PAGES", pRC_MAX_PAGES) :
                new ObjectParameter("PRC_MAX_PAGES", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SEARCH_BOOKS_BYPAGERANGE", pRC_MIN_PAGESParameter, pRC_MAX_PAGESParameter);
        }
    
        public virtual int SEARCH_BOOKS_BYYEAR_OF_PUBLICATION(Nullable<decimal> pRC_MIN_YEAR, Nullable<decimal> pRC_MAX_YEAR)
        {
            var pRC_MIN_YEARParameter = pRC_MIN_YEAR.HasValue ?
                new ObjectParameter("PRC_MIN_YEAR", pRC_MIN_YEAR) :
                new ObjectParameter("PRC_MIN_YEAR", typeof(decimal));
    
            var pRC_MAX_YEARParameter = pRC_MAX_YEAR.HasValue ?
                new ObjectParameter("PRC_MAX_YEAR", pRC_MAX_YEAR) :
                new ObjectParameter("PRC_MAX_YEAR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SEARCH_BOOKS_BYYEAR_OF_PUBLICATION", pRC_MIN_YEARParameter, pRC_MAX_YEARParameter);
        }
    
        public virtual int SEARCH_BOOKS_BYYEARRANGE(Nullable<decimal> pRC_MIN_YEAR, Nullable<decimal> pRC_MAX_YEAR)
        {
            var pRC_MIN_YEARParameter = pRC_MIN_YEAR.HasValue ?
                new ObjectParameter("PRC_MIN_YEAR", pRC_MIN_YEAR) :
                new ObjectParameter("PRC_MIN_YEAR", typeof(decimal));
    
            var pRC_MAX_YEARParameter = pRC_MAX_YEAR.HasValue ?
                new ObjectParameter("PRC_MAX_YEAR", pRC_MAX_YEAR) :
                new ObjectParameter("PRC_MAX_YEAR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SEARCH_BOOKS_BYYEARRANGE", pRC_MIN_YEARParameter, pRC_MAX_YEARParameter);
        }
    
        public virtual int TESTENTER(string eNTEREDLOGINN, string eNTEREDPASSWORDD)
        {
            var eNTEREDLOGINNParameter = eNTEREDLOGINN != null ?
                new ObjectParameter("ENTEREDLOGINN", eNTEREDLOGINN) :
                new ObjectParameter("ENTEREDLOGINN", typeof(string));
    
            var eNTEREDPASSWORDDParameter = eNTEREDPASSWORDD != null ?
                new ObjectParameter("ENTEREDPASSWORDD", eNTEREDPASSWORDD) :
                new ObjectParameter("ENTEREDPASSWORDD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TESTENTER", eNTEREDLOGINNParameter, eNTEREDPASSWORDDParameter);
        }
    
        public virtual int UPDATE_AUTHORS2(string pRC_AUTHOR, string pRC_FULLNAME, Nullable<decimal> pRC_BIRTHYEAR, string pRC_BIRTHCOUNTRY)
        {
            var pRC_AUTHORParameter = pRC_AUTHOR != null ?
                new ObjectParameter("PRC_AUTHOR", pRC_AUTHOR) :
                new ObjectParameter("PRC_AUTHOR", typeof(string));
    
            var pRC_FULLNAMEParameter = pRC_FULLNAME != null ?
                new ObjectParameter("PRC_FULLNAME", pRC_FULLNAME) :
                new ObjectParameter("PRC_FULLNAME", typeof(string));
    
            var pRC_BIRTHYEARParameter = pRC_BIRTHYEAR.HasValue ?
                new ObjectParameter("PRC_BIRTHYEAR", pRC_BIRTHYEAR) :
                new ObjectParameter("PRC_BIRTHYEAR", typeof(decimal));
    
            var pRC_BIRTHCOUNTRYParameter = pRC_BIRTHCOUNTRY != null ?
                new ObjectParameter("PRC_BIRTHCOUNTRY", pRC_BIRTHCOUNTRY) :
                new ObjectParameter("PRC_BIRTHCOUNTRY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_AUTHORS2", pRC_AUTHORParameter, pRC_FULLNAMEParameter, pRC_BIRTHYEARParameter, pRC_BIRTHCOUNTRYParameter);
        }
    
        public virtual int UPDATE_BOOKINF(Nullable<decimal> pROC_BOOK_ID, string uPDATEBOOKNAME, Nullable<decimal> uPDATEBOOKPAGES, string uPDATEBOOKISBN, string uPDATEBOOKBINDING, Nullable<decimal> uPDATEBOOKYEARPUBLIC, Nullable<decimal> uPDATEBOOKIDPUBLISHHOUS, string uPDATEBOOKLANGUAGE, string uPDATEBOOKDESCRIPT, string uPDATEBOOKIMAGESOURSCE, Nullable<decimal> uPDATEBOOKNUMBERSOFBOOKS, Nullable<decimal> uPDATEBOOKPRICE)
        {
            var pROC_BOOK_IDParameter = pROC_BOOK_ID.HasValue ?
                new ObjectParameter("PROC_BOOK_ID", pROC_BOOK_ID) :
                new ObjectParameter("PROC_BOOK_ID", typeof(decimal));
    
            var uPDATEBOOKNAMEParameter = uPDATEBOOKNAME != null ?
                new ObjectParameter("UPDATEBOOKNAME", uPDATEBOOKNAME) :
                new ObjectParameter("UPDATEBOOKNAME", typeof(string));
    
            var uPDATEBOOKPAGESParameter = uPDATEBOOKPAGES.HasValue ?
                new ObjectParameter("UPDATEBOOKPAGES", uPDATEBOOKPAGES) :
                new ObjectParameter("UPDATEBOOKPAGES", typeof(decimal));
    
            var uPDATEBOOKISBNParameter = uPDATEBOOKISBN != null ?
                new ObjectParameter("UPDATEBOOKISBN", uPDATEBOOKISBN) :
                new ObjectParameter("UPDATEBOOKISBN", typeof(string));
    
            var uPDATEBOOKBINDINGParameter = uPDATEBOOKBINDING != null ?
                new ObjectParameter("UPDATEBOOKBINDING", uPDATEBOOKBINDING) :
                new ObjectParameter("UPDATEBOOKBINDING", typeof(string));
    
            var uPDATEBOOKYEARPUBLICParameter = uPDATEBOOKYEARPUBLIC.HasValue ?
                new ObjectParameter("UPDATEBOOKYEARPUBLIC", uPDATEBOOKYEARPUBLIC) :
                new ObjectParameter("UPDATEBOOKYEARPUBLIC", typeof(decimal));
    
            var uPDATEBOOKIDPUBLISHHOUSParameter = uPDATEBOOKIDPUBLISHHOUS.HasValue ?
                new ObjectParameter("UPDATEBOOKIDPUBLISHHOUS", uPDATEBOOKIDPUBLISHHOUS) :
                new ObjectParameter("UPDATEBOOKIDPUBLISHHOUS", typeof(decimal));
    
            var uPDATEBOOKLANGUAGEParameter = uPDATEBOOKLANGUAGE != null ?
                new ObjectParameter("UPDATEBOOKLANGUAGE", uPDATEBOOKLANGUAGE) :
                new ObjectParameter("UPDATEBOOKLANGUAGE", typeof(string));
    
            var uPDATEBOOKDESCRIPTParameter = uPDATEBOOKDESCRIPT != null ?
                new ObjectParameter("UPDATEBOOKDESCRIPT", uPDATEBOOKDESCRIPT) :
                new ObjectParameter("UPDATEBOOKDESCRIPT", typeof(string));
    
            var uPDATEBOOKIMAGESOURSCEParameter = uPDATEBOOKIMAGESOURSCE != null ?
                new ObjectParameter("UPDATEBOOKIMAGESOURSCE", uPDATEBOOKIMAGESOURSCE) :
                new ObjectParameter("UPDATEBOOKIMAGESOURSCE", typeof(string));
    
            var uPDATEBOOKNUMBERSOFBOOKSParameter = uPDATEBOOKNUMBERSOFBOOKS.HasValue ?
                new ObjectParameter("UPDATEBOOKNUMBERSOFBOOKS", uPDATEBOOKNUMBERSOFBOOKS) :
                new ObjectParameter("UPDATEBOOKNUMBERSOFBOOKS", typeof(decimal));
    
            var uPDATEBOOKPRICEParameter = uPDATEBOOKPRICE.HasValue ?
                new ObjectParameter("UPDATEBOOKPRICE", uPDATEBOOKPRICE) :
                new ObjectParameter("UPDATEBOOKPRICE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_BOOKINF", pROC_BOOK_IDParameter, uPDATEBOOKNAMEParameter, uPDATEBOOKPAGESParameter, uPDATEBOOKISBNParameter, uPDATEBOOKBINDINGParameter, uPDATEBOOKYEARPUBLICParameter, uPDATEBOOKIDPUBLISHHOUSParameter, uPDATEBOOKLANGUAGEParameter, uPDATEBOOKDESCRIPTParameter, uPDATEBOOKIMAGESOURSCEParameter, uPDATEBOOKNUMBERSOFBOOKSParameter, uPDATEBOOKPRICEParameter);
        }
    }
}
