//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        public Nullable<decimal> ID_ORDERS { get; set; }
        public Nullable<decimal> ID_BOOK { get; set; }
        public decimal NUMBERORDEREDBOOKS { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual ORDERINF ORDERINF { get; set; }
    }
}
