//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERINF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERINF()
        {
            this.ORDERS = new HashSet<ORDERS>();
        }
    
        public decimal ID_ORDER { get; set; }
        public Nullable<decimal> ID_USER { get; set; }
        public System.DateTime ORDER_DATE { get; set; }
        public System.DateTime DELIVERY_TIME { get; set; }
        public decimal AMOUNT { get; set; }
    
        public virtual USERINF USERINF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS> ORDERS { get; set; }
    }
}
