//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERACCOUNT
    {
        public decimal ID_ACCOUNT { get; set; }
        public Nullable<decimal> ID_USERAC { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual USERINF USERINF { get; set; }
    }
}
